{
  "openapi": "3.0.3",
  "info": {
    "title": "Aplikasi Todo",
    "description": "Ini adalah api sederhana untuk latihan membuat backend",
     "termsOfService": "https://aplikasi-todo.com/terms/",
    "contact": {
      "name": "zulfikar",
      "email": "isnaen70@gmail.com"
    },
    "license": {
      "name": "MIT",
      "url": "https://opensource.org/license/mit/"
    },
    "version": "1.0.11"
   },
   "externalDocs": {
     "description": "Cari tahu lebih lanjut mengenai Aplikasi todo",
     "url": "https://aplikasi-todo.com/about/"
   },
  "servers": [
     {
       "description": "Todo API Server",
       "url": "https://{env}.aplikasi-todo.com/api",
       "variables": {
         "env": {
           "description": "Server Environment",
           "default": "dev",
           "enum": [
             "dev",
             "qa",
             "prod"
           ]
         }
       }
     }
   ],
   "tags": [
     {
       "name": "Todo",
       "description": "Berkaitan dengan todo",
       "externalDocs": {
         "description": "Cari tahu tentang todo app",
         "url": "https//aplikasi-todo.com"
       }
     },
     {
       "name": "Auth",
       "description": "Untuk Login Aplikasi",
       "externalDocs": {
         "description": "Lebih lanjut tentang Cookie Auth",
         "url": "https//aplikasi-todo.com"
       }
     }
   ],
   "paths": {
     "/todo": {
       "get": {
         "security": [
           {
             "todoCookieAuth": []
           }
         ],
         "tags": ["Todo"],
         "summary": "Ambil semua todo",
         "description": "Ambil semua todo",
         "parameters": [
           {
             "name": "done",
             "in": "query",
             "required": false,
             "description": "Ambil todo yang sudah selesai",
             "schema": {
               "type": "boolean",
               "nullable": true,
               "default": false
             }
           }
         ],
         "responses": {
           "200": {
             "description": "Berhasil mendapatkan semua todo",
             "content": {
               "application/json": {
                 "schema": {
                   "$ref": "#/components/schemas/Response"
                 },
                 "examples": {
                   "success": {
                     "description": "Contoh berhasil mendapatkan semua todo",
                     "value": {
                       "success": true,
                       "message": "success get all record",
                       "result": [
                         {
                           "id": 1,
                           "name": "Todo 1",
                           "description": "Todo pertama saya"
                         },
                         {
                           "id": 2,
                           "name": "Todo 2",
                           "description": "Todo kedua saya"
                         }
                       ],
                       "error": null,
                       "meta": {
                          "count": 1,
                          "total": 1,
                          "lastCursor": 4,
                          "totalPage": 1
                       }
                     }
                   }
                 }
               }
             }
           }
         }
       },
       "post": {
         "security": [
          {
            "todoCookieAuth": []
          }
         ],
         "tags": [
           "Todo"
         ],
         "summary": "Membuat todo baru",
         "description": "Digunakan untuk membuat todo baru",
         "requestBody": {
           "required": true,
           "content": {
             "application/json": {
               "schema": {
                 "$ref": "#/components/schemas/CreateOrUpdateTodo"
               },
               "examples": {
                 "todo 1": {
                   "description": "contoh todo 1",
                   "value": {
                     "name": "zulfikar todo 1",
                     "description": "Ini todo 1 zulfikar"
                   }
                },
                 "todo 2": {
                   "description": "contoh todo 2",
                   "value": {
                     "name": "zulfikar todo 2",
                     "description": "Ini todo 2 zulfikar"
                   }
                 }
               }
             }
           }
         },
         "responses": {
           "200": {
             "description": "Berhasil membuat todo",
             "content": {
               "application/json": {
                 "schema": {
                   "$ref": "#/components/schemas/Response"
                 },
                 "examples": {
                   "todo 1": {
                      "description": "contoh todo 1",
                      "value": {
                        "success": true,
                        "message": "Berhasil membuat todo!",
                        "result": {
                          "id": "1",
                          "name": "zulfikar todo 1",
                          "description": "Ini todo 1 zulfikar"
                        },
                        "error": null,
                        "meta": {}
                      }
                    },
                    "todo 2": {
                      "description": "contoh todo 2",
                      "value": {
                        "success": true,
                        "message": "Berhasil membuat todo!",
                        "result": {
                          "id": "1",
                          "name": "zulfikar todo 2",
                          "description": "Ini todo 2 zulfikar"
                        },
                        "error": null,
                        "meta": {}
                      }
                    }
                 }
               }
             }
           }
         }
       }
     },
     "/todo/{id}": {
       "put": {
         "security": [
          {
            "todoCookieAuth": []
          }
         ],
         "tags": ["Todo"],
         "summary": "Mengubah todo yang sudah ada",
         "description": "Mengubah todo yang sudah ada menggunakan id",
         "parameters": [
           {
             "$ref": "#/components/parameters/TodoId"
           }
         ],
         "requestBody": {
           "required": true,
           "content": {
             "application/json": {
               "schema": {
                 "$ref": "#/components/schemas/CreateOrUpdateTodo"
               },
               "examples": {
                 "todo 1": {
                   "description": "contoh todo 1",
                   "value": {
                     "name": "zulfikar todo 1",
                     "description": "Ini todo 1 zulfikar"
                   }
                 },
                 "todo 2": {
                   "description": "contoh todo 2",
                   "value": {
                     "name": "zulfikar todo 2",
                     "description": "Ini todo 2 zulfikar"
                   }
                 }
               }
             }
           }
         },
         "responses": {
           "200": {
             "description": "Berhasil mengubah todo",
             "content": {
               "application/json": {
                 "schema": {
                   "$ref": "#/components/schemas/Response"
                 },
                 "examples": {
                   "todo 1": {
                      "description": "contoh todo 1",
                      "value": {
                        "success": true,
                        "message": "Berhasil mengubah todo!",
                        "result": {
                          "id": "1",
                          "name": "zulfikar todo 1",
                          "description": "Ini todo 1 zulfikar"
                        },
                        "error": null,
                        "meta": {}
                      }
                    },
                    "todo 2": {
                      "description": "contoh todo 2",
                      "value": {
                        "success": true,
                        "message": "Berhasil mengubah todo!",
                        "result": {
                          "id": "1",
                          "name": "zulfikar todo 2",
                          "description": "Ini todo 2 zulfikar"
                        },
                        "error": null,
                        "meta": {}
                      }
                    }
                 }
               }
             }
           }
         }
       },
       "delete": {
         "security": [
           {
             "todoCookieAuth": []
           }
         ],
         "tags": ["Todo"],
         "summary": "Menghapus todo yang sudah ada",
         "description": "Menghapus todo yang sudah ada menggunakan id",
         "parameters": [
           {
             "$ref": "#/components/parameters/TodoId"
           }
         ],
         "responses": {
           "200": {
             "description": "Berhasil menghapus todo",
             "content": {
               "application/json": {
                 "schema": {
                   "$ref": "#/components/schemas/Response"
                 },
                 "example": {
                    "description": "contoh todo 1",
                    "value": {
                      "success": true,
                      "message": "Berhasil menghapus todo!",
                      "result": {
                        "id": "1",
                        "name": "zulfikar todo 1",
                        "description": "Ini todo 1 zulfikar"
                      },
                      "error": null,
                      "meta": {}
                    }
                  }
                }
             }
           },
           "404": {
             "description": "Gagal menghapus todo, karena tidak dapat di temukan",
             "content": {
               "application/json": {
                 "schema": {
                   "$ref": "#/components/schemas/Response"
                 },
                 "examples": {
                   "Gagal Menghapus": {
                      "description": "Gagal menghapus todo",
                      "value": {
                        "success": true,
                        "message": "Gagal menghapus todo!",
                        "result": null,
                        "error": {
                          "code": 404,
                          "message": "Todo tidak ditemukan!",
                          "params": {}
                        },
                        "meta": {}
                    }
                   }
                 }
               }
             }
           }
         }
       }
     },
     "/login": {
       "post": {
         "security": [
            {
              "todoCookieAuth": []
            }
          ],
          "tags": ["Auth"],
          "summary": "Login Aplikasi",
          "description": "Untuk Login Aplikasi dan mendapatkan session",
          "requestBody": {
            "required": true,
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Login"
                },
                "examples": {
                  "User Zul": {
                    "description": "Contoh User 1",
                    "value": {
                      "email": "isnaen@gmail.com",
                      "password": "pass123"
                    }
                  },
                  "User Dony": {
                    "description": "Contoh User 2",
                    "value": {
                      "email": "dony@gmail.com",
                      "password": "pass123"
                    }
                  }
                }
              }
            }
          },
          "responses": {
            "200": {
              "description": "Login Berhasil",
              "headers": {
                "Set-Cookie": {
                  "schema": {
                    "type": "string",
                    "example": "SESSION_TOKEN=abcde12345; Path=/; HttpOnly"
                  }
                }
              },
              "content": {
               "application/json": {
                 "schema": {
                   "$ref": "#/components/schemas/Response"
                 },
                 "examples": {
                   "User A": {
                     "description": "contoh Berhasil Login",
                     "value": {
                        "success": true,
                        "message": "Login Berhasil!",
                        "result": {
                          "id": 24,
                          "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiVTJGc2RHVmtYMThvcEN1cFNTbHlLVHJId3o2RUNoeThKVkhIU21GNlZiOERPVlVCYVh4T0pocWFZdjNwYW1UWTBwMUhhJTJCblN1V2hDbXQwWW5aemk1TDZxR09Jd2hWNE1icjFoWW81YTg5c1c2eFpkWTJwM3hjdzdDOXZOJTJGSHElMkZ4bTZJN1VrUUgzbDhtQiUyRlhzUXdhRkhaU01HMU4yaFglMkZoaWxJSURBSXc4TzFRRDFXeHhCc0MxRm53UVNHVWtjMyUyRlFOZDdOSCUyQkROYzBKM215WXJJJTJGeCUyRjcxaW1TZXpIRVozMVk2RlRuc29Temoyd0Z0MmdDUEJsNjVSR1ZSM2IlMkI4IiwiaWF0IjoxNjc5NTIxNzQ0LCJleHAiOjE2Nzk3ODA5NDQsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6NDAwMCIsImlzcyI6Inp1bGZpa2FyLWJsb2ciLCJzdWIiOiI2In0.e2lFdKVRWWRIlY2dbOhr0MhwagqmOq0mQ1eRlv9rmJU",
                          "refresh": "f51784937ad44025ee2704ac936fcf73f9a298ac055a94b8400f3a90a0519e724473b1e8808cdbcf60529dd4299accf8a1c129904dae818dd7221246f60f07c",
                          "expiredAt": "2023-04-21T21:49:04.358Z"
                        },
                        "error": null,
                        "meta": {}
                     }
                   }
                 }
               }
             }
            },
            "404": {
              "description": "Login Failed",
              "content": {
               "application/json": {
                 "schema": {
                   "$ref": "#/components/schemas/Response"
                 },
                 "examples": {
                   "Gagal Login": {
                     "description": "contoh Gagal Login",
                     "value": {
                        "success": false,
                        "message": "Gagal Login!",
                        "result": null,
                        "error": {
                          "code": 404,
                          "message": "User not found!",
                          "params": {}
                        }
                     }
                   }
                 }
               }
             }
            }
          }
       }
     }
   },
   "components": {
     "schemas": {
       "Response": {
         "type": "object",
         "properties": {
            "success": {
              "type": "boolean",
              "description": "status hasil berhasil atau tidak"
            },
            "message": {
              "type": "string",
              "description": "Message result"
            },
            "result": {
              "oneOf": [
                {"type": "array"},
                {"type": "object", "additionalProperties": true}
              ],
              "items": {
                "oneOf": [
                    {"$ref": "#/components/schemas/Todo"}
                ]
              }
            },
            "error": {
              "type": "object",
              "additionalProperties": true,
              "properties": {
                "code": {
                  "type": "integer",
                  "format": "int64"
                },
                "params": {
                  "type": "object",
                  "additionalProperties": true
                }
              }
            },
            "meta": {
              "type": "object",
              "description": "meta data",
              "additionalProperties": true
            }
         }
       },
       "Todo": {
         "type": "object",
         "properties": {
           "id": {
             "type": "integer",
             "format": "int64"
           },
           "name": {
             "type": "string",
             "description": "nama todonya"
           },
           "description": {
             "type": "string",
             "description": "ini deskripsi todo"
           }
         }
       },
       "CreateOrUpdateTodo": {
         "type": "object",
         "properties": {
           "name": {
             "type": "string",
             "description": "nama todonya"
           },
           "description": {
             "type": "string",
             "description": "ini deskripsi todo"
           }
         }
       },
       "Login": {
         "type": "object",
         "properties": {
           "email": {
             "type": "string",
             "description": "email untuk login"
           },
           "password": {
             "type": "string",
             "format": "password",
             "description": "password untuk login"
           }
         }
       }
     },
     "securitySchemes": {
       "todoCookieAuth": {
         "type": "apiKey",
         "in": "cookie",
         "name": "SESSION_TOKEN"
       }
     },
     "parameters": {
       "TodoId": {
         "name": "id",
         "in": "path",
         "required": true,
         "description": "Todo Id for update or delete",
         "schema": {
           "type": "integer",
           "format": "int64"
         },
         "examples": {
           "todo 1": {
             "description": "Sample todo id for todo 1",
             "value": 1
           },
           "todo 2": {
             "description": "Sample todo id for todo 2",
             "value": 2
           }
         }
       }
     }
   }
 }